### ISSUE TITLE
Consideraciones para limpiar el repo

### ISSUE THREAD

**Issue by Adrito981119** [MiguelAntonioRS/Gestion-Project-of-Buys-and-Sales#1]
**Readme.md**
1. Usualmente estos frameworks tienen un CLI o alguna forma de interfaz que permite agilizar el proceso de instalar dependencias.
2. Un IDE no es una dependencia, quien entra aqui ya tiene el suyo.
3. El proceso de navegar a un directorio puede resumirse en un solo paso. Ejemplo:
 `cd src\com\capaPresentacion`

**Estructura de ficheros**
No estoy familiarizado con Java o la plataforma que usas pero a grossa vista parece usar un patron Modelo Vista - Vista Modelo (MVVM). No es una camisa de fuerza, pero hay una convencion bastante comun en estos sistemas que funciona mas menos asi.

Los ficheros xml como por ejemplo FrmBuy.form lo puedes renombrar a FrmBuyView.form, para su archivo .java le puedes poner FrmBuyModel.java, repito no es una camisa de fuerza, pero el que es nuevo en este patron puede enredarse.

**Ficheros innecesarios**
Añade un archivo .gitignore para que excluyas del repo cualquier archivo que no deba estar aca, un ejemplo son los fichero output de la compilacion que son innecesarios, mas aun para un dev cubano que tenga que descargar esto con sus datos.

**Comment by MiguelAntonioRS** [comment]
Buenos consejos gracias 🙏🏼
